version: "3.3" # Defines the Docker Compose file format version

services:
  # Service Discovery: Keeps track of all microservices
  eureka-server:
    build: # Instructions for building a custom image from a local directory
      context: ./EurekaService # The directory containing the build files
      dockerfile: Dockerfile  # The specific file used to build the image
    image: eureka-server:latest # The name and tag given to the resulting image
    ports: # Maps host machine ports to container ports (HOST:CONTAINER)
      - "8761:8761"
    healthcheck: # A test to check if the container is running correctly
      # test: The actual command executed to verify the container's health
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 20s # How often to run the check
      timeout: 10s # How long to wait for a response
      retries: 5 # Number of failures before marking as unhealthy

  gateway-api:
    build:
      context: ./GatewayService
      dockerfile: Dockerfile
    image: gateway-api:latest
    environment: # Sets environment variables inside the container
      # Key-Value pairs used to configure the application environment at runtime
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    depends_on: # Ensures this service starts only after the listed services are running
      - eureka-server
    ports:
      - "9003:9000"

  player-recommendation-service:
    build:
      context: ./PlayerRecommendationService
      dockerfile: Dockerfile
    image: player-recommendation-service:latest
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_NEO4J_URI=bolt://neo4j-player-recommendation:7600
      - SPRING_NEO4J_AUTHENTICATION_USERNAME=neo4j
      - SPRING_NEO4J_AUTHENTICATION_PASSWORD=password
    depends_on:
      eureka-server:
        condition: service_healthy
      neo4j-player-recommendation:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "9060:9060"

  neo4j-player-recommendation:
    image: neo4j:5
    ports:
      - "7500:7500"
      - "7600:7600"
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_server_http_listen__address: ":7500"
      NEO4J_server_bolt_listen__address: ":7600"
      NEO4J_server_http_advertised__address: "neo4j-player-recommendation:7500"
      NEO4J_server_bolt_advertised__address: "neo4j-player-recommendation:7600"
    volumes:
      - neo4j_player_recommendation_data:/data
    healthcheck:
      test: [ "CMD", "cypher-shell", "-a", "bolt://localhost:7600", "-u", "neo4j", "-p", "password", "RETURN 1" ]
      interval: 20s
      timeout: 10s
      retries: 5

  ticket-sales-service:
    build:
      context: ./TicketSalesService
      dockerfile: Dockerfile
    image: ticket-sales-service:latest
    depends_on:
      eureka-server:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_NEO4J_URI: bolt://neo4j:7687
      SPRING_NEO4J_AUTHENTICATION_USERNAME: neo4j
      SPRING_NEO4J_AUTHENTICATION_PASSWORD: password
    ports:
      - "9070:9070"

  ticket-search-service:
    build:
      context: ./TicketSearchService
      dockerfile: Dockerfile
    image: ticket-search-service:latest
    depends_on:
      eureka-server:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      ELASTICSEARCH_URIS: http://elasticsearch:9200
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "9071:9071"

  elasticsearch:
    image: elasticsearch:8.11.0
    ports:
      - "9201:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 20s
      timeout: 10s
      retries: 5

  neo4j:
    image: neo4j:5
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes: # Mounts persistent storage or local folders into the container
      - neo4j_data:/data
    healthcheck:
      test: [ "CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "RETURN 1" ]
      interval: 20s
      timeout: 10s
      retries: 5

  player-info-service:
    build:
      context: ./PlayerInfoService
      dockerfile: Dockerfile
    image: player-info-service:latest
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_ELASTICSEARCH_URIS=http://player-info-db:9200
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      eureka-server:
        condition: service_healthy
      player-info-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "9090:9090"


  player-info-db:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: player-info-db
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - player_info_data:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"\\|\"status\":\"yellow\"'" ]
      interval: 10s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: kibana
    ports:
      - "5601:5601"                          
    environment:
      - ELASTICSEARCH_HOSTS=http://player-info-db:9200
      - XPACK_SECURITY_ENABLED=false
    depends_on:
      player-info-db:
        condition: service_healthy

  neo4j-recommended:
    image: neo4j:5
    ports:
      - "7475:7474"
      - "7688:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j_recommended_data:/data
    healthcheck:
      test: [ "CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "RETURN 1" ]
      interval: 20s
      timeout: 10s
      retries: 5

  recommended-activity-service:
    build:
      context: ./RecommendedActivityService
      dockerfile: Dockerfile
    image: recommended-activity-service:latest
    depends_on:
      neo4j-recommended:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_NEO4J_URI: bolt://neo4j-recommended:7687
      SPRING_NEO4J_AUTHENTICATION_USERNAME: neo4j
      SPRING_NEO4J_AUTHENTICATION_PASSWORD: password
      SPRING_RABBITMQ_HOST: rabbitmq
    ports:
      - "9080:8080"

  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password12345
      - DOCKER_INFLUXDB_INIT_ORG=nais_org 
      - DOCKER_INFLUXDB_INIT_BUCKET=nais_bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-token-12345
    volumes:
      - influxdb_data:/var/lib/influxdb2
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8086/health" ]
      interval: 20s
      timeout: 10s
      retries: 5

  live-match-service:
    build:
      context: ./LiveMatchService
      dockerfile: Dockerfile
    image: live-match-service:latest
    ports:
      - "9000:9000"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=my-super-secret-token-12345
      - DOCKER_INFLUXDB_INIT_ORG=nais_org 
      - DOCKER_INFLUXDB_INIT_BUCKET=nais_bucket
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      eureka-server:
        condition: service_healthy
      influxdb:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  redis:
    image: redis:7.2-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/db
    depends_on:
      - redis

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management Web UI port
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "check_running" ]
      interval: 10s
      timeout: 5s
      retries: 3

  grafana:
    image: grafana/grafana:latest
    user: "0"
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      # --- PLUGIN INSTALLATION ---
      # ove dodati plug-ins koji su potrebni
      - GF_PLUGINS_PREINSTALL=elasticsearch,kniepdennis-neo4j-datasource
      - GF_INSTALL_PLUGINS=elasticsearch,kniepdennis-neo4j-datasource
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana_storage:/var/lib/grafana

volumes:
  neo4j_player_recommendation_data: {}
  neo4j_data: {}
  neo4j_recommended_data: {}
  influxdb_data: {}
  player_info_data: {}
  elasticsearch_data: {}
  redis_data: {}
  redisinsight_data: {}
  rabbitmq_data: {}
  grafana_storage: {}
