spring.application.name=PlayerInfoService
spring.elasticsearch.uris=${SPRING_ELASTICSEARCH_URIS:player-info-db:9200}
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka}
eureka.instance.non-secure-port=9090
server.port=9090
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=player-info-service
server.forward-headers-strategy=framework
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.cache.type=redis
