spring.application.name=demospring.application.name=demo
server.port=9000
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
